/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { db } from './db.js';
import { Opportunity } from '../src/types.js';

/**
 * Send a message via the Telegram Bot API safely.
 */
export async function sendTelegramMessage(message: string): Promise<boolean> {
  const settings = db.getTelegramSettings();
  if (!settings.enabled || !settings.botToken || !settings.chatId) {
    // Gracefully skip if Telegram is offline/incomplete
    return false;
  }

  try {
    const response = await fetch(
      `https://api.telegram.org/bot${settings.botToken}/sendMessage`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          chat_id: settings.chatId,
          text: message,
          parse_mode: 'Markdown',
        }),
      }
    );

    const result = await response.json() as any;
    if (result.ok) {
      db.addLog('success', 'telegram', 'Notification successfully dispatched via Telegram Bot.');
      return true;
    } else {
      db.addLog(
        'warning',
        'telegram',
        `Telegram endpoint returned rejection: ${result.description || 'Unknown error'}`
      );
      return false;
    }
  } catch (err: any) {
    db.addLog(
      'error',
      'telegram',
      `Failed to connect to Telegram server: ${err?.message || 'Connection refused'}`
    );
    return false;
  }
}

/**
 * Formulate and send an alert for a high-compatibility job match.
 */
export async function sendJobMatchAlert(op: Opportunity, score: number): Promise<boolean> {
  const settings = db.getTelegramSettings();
  if (!settings.notifyOnNewMatch) return false;

  const text = `
🔥 *New High Match Opportunity Found!*
----------------------------------------
*Platform*: ${op.platform}
*Match Score*: ⭐ *${score}%*
*Job Title*: ${op.title}
*Estimated Budget*: ${op.budget}

*Description Summary*:
_${op.description.substring(0, 180)}..._

*Action*:
[Open Job Description on ${op.platform}](${op.link})

⚡ _Generated by Freelance OS Automated Scanner_
  `;

  return sendTelegramMessage(text.trim());
}

/**
 * Formulate and send a report summarizing daily activities.
 */
export async function sendDailyBriefingReport(): Promise<boolean> {
  const ops = db.getOpportunities();
  const props = db.getProposals();
  const profile = db.getProfile();

  const todayStr = new Date().toDateString();

  // Calculate metrics for today
  const matches = ops.filter(o => o.matchAnalysis && o.matchAnalysis.score >= 70);
  const bestMatches = [...matches]
    .sort((a, b) => (b.matchAnalysis?.score || 0) - (a.matchAnalysis?.score || 0))
    .slice(0, 3);

  const submittedCount = props.filter(p => p.status === 'submitted').length;
  const draftCount = props.filter(p => p.status === 'draft').length;

  const text = `
📊 *Freelance OS - Daily AI Briefing*
📅 *Date: ${todayStr}*
----------------------------------------

📋 *Opportunities Summary:*
• Scan Status: Active (3 Platforms)
• Match Threshold: 70%+ Score
• Best Opportunities Highlighted: ${bestMatches.length}

${bestMatches.map((bm, index) => `${index + 1}. [${bm.platform}] *${bm.title}* (${bm.budget}) - Match Score: *${bm.matchAnalysis?.score}%*`).join('\n') || '• No high-match jobs found today yet.'}

📝 *Work Progress:*
• Proposals Generated: ${props.length}
• Draft Queue: ${draftCount}
• Proposals Submitted: ${submittedCount}

💡 *AI Tactical Recommendations:*
- Focus outreach efforts on *${bestMatches[0]?.platform || 'Mostaql'}* projects for maximum reply probability.
- Keep hourly rate stable at *$${profile.hourlyRate}/hr* as target categories are reporting active bids.
- Purge proposal outbox every 4 hours to bypass platform anti-spam rate caps.

🚀 _Stay productive!_
  `;

  db.addLog('info', 'telegram', 'Dispatched daily AI briefing report manually.');
  return sendTelegramMessage(text.trim());
}

/**
 * Active Scheduler check loop to call daily briefing
 */
let schedulerIntervalId: NodeJS.Timeout | null = null;
let lastBriefingDateStr = '';

export function startScheduler() {
  if (schedulerIntervalId) {
    clearInterval(schedulerIntervalId);
  }

  // Check every 6s (60000ms is real clock check, let's run every 1 minute)
  schedulerIntervalId = setInterval(async () => {
    const settings = db.getTelegramSettings();
    if (!settings.enabled || !settings.botToken || !settings.chatId) return;

    const now = new Date();
    const currentHourMin = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;
    const todayDateStr = now.toDateString();

    if (currentHourMin === settings.reportTime && lastBriefingDateStr !== todayDateStr) {
      lastBriefingDateStr = todayDateStr;
      db.addLog('info', 'telegram', `Triggering scheduled Daily Briefing Report at ${settings.reportTime}`);
      await sendDailyBriefingReport();
    }
  }, 60000);
}
