/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { db } from './db.js';
import { Opportunity } from '../src/types.js';

export function escapeMarkdown(str: string): string {
  if (!str) return '';
  return str
    .replace(/\\/g, '\\\\')
    .replace(/\*/g, '\\*')
    .replace(/_/g, '\\_')
    .replace(/\[/g, '\\[')
    .replace(/\]/g, '\\]')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
    .replace(/`/g, '\\`');
}

export function escapeHtml(str: string): string {
  if (!str) return '';
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

/**
 * Send a message via the Telegram Bot API safely.
 */
export async function sendTelegramMessage(message: string, parseMode: 'HTML' | 'Markdown' = 'HTML'): Promise<boolean> {
  const settings = db.getTelegramSettings();
  if (!settings.enabled || !settings.botToken || !settings.chatId) {
    // Gracefully skip if Telegram is offline/incomplete
    return false;
  }

  try {
    const response = await fetch(
      `https://api.telegram.org/bot${settings.botToken}/sendMessage`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          chat_id: settings.chatId,
          text: message,
          parse_mode: parseMode,
        }),
      }
    );

    const result = await response.json() as any;
    if (result.ok) {
      db.addLog('success', 'telegram', 'Notification successfully dispatched via Telegram Bot.');
      return true;
    } else {
      db.addLog(
        'warning',
        'telegram',
        `Telegram endpoint returned rejection: ${result.description || 'Unknown error'}`
      );
      return false;
    }
  } catch (err: any) {
    db.addLog(
      'error',
      'telegram',
      `Failed to connect to Telegram server: ${err?.message || 'Connection refused'}`
    );
    return false;
  }
}

/**
 * Send custom reply direct in chatbot thread.
 */
async function sendReply(chatId: string, replyText: string, parseMode: 'HTML' | 'Markdown' = 'HTML'): Promise<boolean> {
  const settings = db.getTelegramSettings();
  if (!settings.botToken) return false;

  try {
    const response = await fetch(
      `https://api.telegram.org/bot${settings.botToken}/sendMessage`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          chat_id: chatId,
          text: replyText,
          parse_mode: parseMode,
          disable_web_page_preview: true
        }),
      }
    );
    const result = await response.json() as any;
    return !!result.ok;
  } catch (err: any) {
    console.error('Failed sending chatbot response:', err);
    return false;
  }
}

/**
 * Formulate and send an alert for a high-compatibility job match.
 */
export async function sendJobMatchAlert(op: Opportunity, score: number): Promise<boolean> {
  const settings = db.getTelegramSettings();
  if (!settings.notifyOnNewMatch) return false;

  const text = `
🔥 <b>New High Match Opportunity Found!</b>
----------------------------------------
<b>Platform</b>: ${escapeHtml(op.platform)}
<b>Match Score</b>: ⭐ <b>${score}%</b>
<b>Job Title</b>: ${escapeHtml(op.title)}
<b>Estimated Budget</b>: ${escapeHtml(op.budget)}

<b>Description Summary</b>:
<i>${escapeHtml(op.description.substring(0, 180))}...</i>

<b>Action</b>:
<a href="${op.link}">Open Job Description on ${escapeHtml(op.platform)}</a>

⚡ <i>Generated by Freelance OS Automated Scanner</i>
  `;

  return sendTelegramMessage(text.trim(), 'HTML');
}

/**
 * Formulate and send a report summarizing daily activities.
 */
export async function sendDailyBriefingReport(): Promise<boolean> {
  const ops = db.getOpportunities();
  const props = db.getProposals();
  const profile = db.getProfile();

  const todayStr = new Date().toDateString();

  // Calculate metrics for today
  const matches = ops.filter(o => o.matchAnalysis && o.matchAnalysis.score >= 70);
  const bestMatches = [...matches]
    .sort((a, b) => (b.matchAnalysis?.score || 0) - (a.matchAnalysis?.score || 0))
    .slice(0, 3);

  const submittedCount = props.filter(p => p.status === 'submitted').length;
  const draftCount = props.filter(p => p.status === 'draft').length;

  const text = `
📊 <b>Freelance OS - Daily AI Briefing</b>
📅 <b>Date: ${todayStr}</b>
----------------------------------------

📋 <b>Opportunities Summary:</b>
• Scan Status: Active (3 Platforms)
• Match Threshold: 70%+ Score
• Best Opportunities Highlighted: ${bestMatches.length}

${bestMatches.map((bm, index) => `${index + 1}. <a href="${bm.link}">[${escapeHtml(bm.platform)}] <b>${escapeHtml(bm.title)}</b></a> (${escapeHtml(bm.budget)}) - Match Score: <b>${bm.matchAnalysis?.score}%</b>`).join('\n') || '• No high-match jobs found today yet.'}

📝 <b>Work Progress:</b>
• Proposals Generated: ${props.length}
• Draft Queue: ${draftCount}
• Proposals Submitted: ${submittedCount}

💡 <b>AI Tactical Recommendations:</b>
- Focus outreach efforts on <b>${bestMatches[0]?.platform || 'Mostaql'}</b> projects for maximum reply probability.
- Keep hourly rate stable at <b>$${profile.hourlyRate}/hr</b> as target categories are reporting active bids.
- Purge proposal outbox every 4 hours to bypass platform anti-spam rate caps.

🚀 <i>Stay productive!</i>
  `;

  db.addLog('info', 'telegram', 'Dispatched daily AI briefing report manually.');
  return sendTelegramMessage(text.trim(), 'HTML');
}

/**
 * Chatbot routing implementation.
 */
async function handleIncomingTelegramMessage(message: any) {
  const chatId = message.chat.id.toString();
  const text = (message.text || '').trim();

  const currentSettings = db.getTelegramSettings();

  // Simple auto-pairing loop if ChatId is empty
  if (!currentSettings.chatId) {
    db.updateTelegramSettings({ chatId });
    db.addLog('success', 'telegram', `Automatically paired Telegram Chat ID to: ${chatId}`);
    await sendReply(chatId, `🎉 <b>Freelance OS Co-Pilot Paired Successfully!</b>\n\nYour Freelance OS Chat ID has been dynamically paired with this chat: <b>${chatId}</b>.\n\nYou are now authenticated to run zero-AI cost command queries or talk with your Gemini agent directly! Try sending <code>/help</code> to browse operational commands.`, 'HTML');
    return;
  }

  // Authorize designated chatId
  if (chatId !== currentSettings.chatId) {
    await sendReply(chatId, `🚫 <b>Access Denied!</b>\n\nThis Chatbot is securely verified with another Freelance OS owner.\n\nYour Chat ID is <b>${chatId}</b>. Only authenticated workspace credentials can query this scheduler agent.`, 'HTML');
    return;
  }

  // Parse Slash Commands with support for bot usernames (@botname)
  if (text.startsWith('/')) {
    const parts = text.split(' ');
    const firstWord = parts[0];
    const match = firstWord.match(/^\/([a-zA-Z0-9_]+)(?:@([a-zA-Z0-9_]+))?(?:\s|$)/);
    const command = match ? '/' + match[1].toLowerCase() : firstWord.toLowerCase();

    if (command === '/start' || command === '/help') {
      const helpMsg = `
🤖 <b>Freelance OS - Telegram Co-Pilot Help</b>

Below is the list of available commands. Note that any querying or platform scraping commands run on local databases and scraping workers without invoking the LLM, protecting your free-tier Gemini API credits!

ℹ️ <b>Detailed Command Explanations:</b>

💵 <b>Platform Queue Queries (ZERO AI Cost):</b>
• <code>/khamsat</code> — Lists the latest 6 freelance projects scraped from Khamsat, including descriptions, budgets, and links. (Uses Database directly)
• <code>/mostaql</code> — Lists the latest 6 active opportunities from Mostaql with project details, matching metrics, and statuses. (Uses Database directly)
• <code>/fiverr</code> — Shows Fiverr platform opportunities and matched gig briefs. (Uses Database directly)
• <code>/profile</code> — Displays your configured freelancer persona, stack, target rates, and exclusions. (Uses Database directly)
• <code>/match</code> — Lists highly compatible projects that match your profile score. (Uses Database directly)
• <code>/status</code> — Confirms continuous backend container health, scraper logs, account connections, and daily metrics. (Uses Database directly)

⚡ <b>Actions & Handlers (ZERO AI Cost unless briefing requested):</b>
• <code>/scrape</code> — Directly starts background crawling threads to grab real-time freelance project requests from all connected platforms. (Uses browser scraper, no AI cost)
• <code>/revalidate</code> — Runs background link checks on all targets to discard expired, closed, or deactivated URLs. (Uses direct HTTP checkers, no AI cost)
• <code>/briefing</code> — Compiles and generates a comprehensive personalized Daily AI summary report of matching leads. <i>(Runs Gemini model - uses AI credits)</i>
• <code>/help</code> — Displays this command menu. (ZERO AI Cost)

💬 <b>Conversational Co-Pilot (Gemini AI Cost):</b>
• Sending any general text message without a slash starts/continues an interactive advice session with your co-pilot.
• <i>"How can I pitch to a client who wants a Node.js scraper?"</i> (Runs Gemini model - uses AI credits)
      `;
      await sendReply(chatId, helpMsg.trim(), 'HTML');
      return;
    }

    if (command === '/khamsat') {
      const ops = db.getOpportunities().filter(o => o.platform.toLowerCase() === 'khamsat');
      if (ops.length === 0) {
        await sendReply(chatId, `📋 <b>Khamsat Jobs Queue</b>\n\nNo Khamsat opportunities are logged in your database yet.\nUse <code>/scrape</code> to find fresh requests!`, 'HTML');
        return;
      }
      const responseLines = [
        `📋 <b>Khamsat Jobs Queue (Latest ${Math.min(ops.length, 6)})</b>`,
        `----------------------------------------`
      ];
      ops.slice(0, 6).forEach((o, i) => {
        const scoreText = o.matchAnalysis ? `⭐ <b>${o.matchAnalysis.score}%</b>` : `<i>Unscored</i>`;
        const healthText = o.validationStatus === 'VALID' ? `✅ Healthy` : `⚠️ ${escapeHtml(o.validationReason || 'Expired')}`;
        responseLines.push(
          `<b>${i + 1}.</b> <a href="${o.link}"><b>${escapeHtml(o.title)}</b></a>\nBudget: <b>${escapeHtml(o.budget)}</b> | Match: ${scoreText}\nStatus: <b>${o.status}</b> | Health: <i>${healthText}</i>`
        );
      });
      await sendReply(chatId, responseLines.join('\n\n'), 'HTML');
      return;
    }

    if (command === '/mostaql') {
      const ops = db.getOpportunities().filter(o => o.platform.toLowerCase() === 'mostaql');
      if (ops.length === 0) {
        await sendReply(chatId, `📋 <b>Mostaql Projects Queue</b>\n\nNo Mostaql projects are logged in your database yet.\nUse <code>/scrape</code> to crawl projects!`, 'HTML');
        return;
      }
      const responseLines = [
        `📋 <b>Mostaql Projects Queue (Latest ${Math.min(ops.length, 6)})</b>`,
        `----------------------------------------`
      ];
      ops.slice(0, 6).forEach((o, i) => {
        const scoreText = o.matchAnalysis ? `⭐ <b>${o.matchAnalysis.score}%</b>` : `<i>Unscored</i>`;
        const healthText = o.validationStatus === 'VALID' ? `✅ Healthy` : `⚠️ ${escapeHtml(o.validationReason || 'Expired')}`;
        responseLines.push(
          `<b>${i + 1}.</b> <a href="${o.link}"><b>${escapeHtml(o.title)}</b></a>\nBudget: <b>${escapeHtml(o.budget)}</b> | Match: ${scoreText}\nStatus: <b>${o.status}</b> | Health: <i>${healthText}</i>`
        );
      });
      await sendReply(chatId, responseLines.join('\n\n'), 'HTML');
      return;
    }

    if (command === '/fiverr') {
      const ops = db.getOpportunities().filter(o => o.platform.toLowerCase() === 'fiverr');
      if (ops.length === 0) {
        await sendReply(chatId, `📋 <b>Fiverr Gigs Queue</b>\n\nNo Fiverr gigs are logged in your database yet.\nUse <code>/scrape</code> to locate services!`, 'HTML');
        return;
      }
      const responseLines = [
        `📋 <b>Fiverr Gigs Queue (Latest ${Math.min(ops.length, 6)})</b>`,
        `----------------------------------------`
      ];
      ops.slice(0, 6).forEach((o, i) => {
        const scoreText = o.matchAnalysis ? `⭐ <b>${o.matchAnalysis.score}%</b>` : `<i>Unscored</i>`;
        const healthText = o.validationStatus === 'VALID' ? `✅ Healthy` : `⚠️ ${escapeHtml(o.validationReason || 'Expired')}`;
        responseLines.push(
          `<b>${i + 1}.</b> <a href="${o.link}"><b>${escapeHtml(o.title)}</b></a>\nPrice: <b>${escapeHtml(o.budget)}</b> | Match: ${scoreText}\nStatus: <b>${o.status}</b> | Health: <i>${healthText}</i>`
        );
      });
      await sendReply(chatId, responseLines.join('\n\n'), 'HTML');
      return;
    }

    if (command === '/profile') {
      const profile = db.getProfile();
      const info = `
👤 <b>Your Freelancer Dashboard Profile</b>
----------------------------------------
• <b>Exp Level</b>: <code>${profile.experience.toUpperCase()}</code>
• <b>Target Budget</b>: <code>Min $${profile.preferredMinBudget}</code>
• <b>Hourly Rate</b>: <code>$${profile.hourlyRate}/hr</code>
• <b>Tone Choice</b>: <code>${profile.proposalTone.toUpperCase()}</code>
• <b>Pitch Length</b>: <code>${profile.proposalLength.toUpperCase()}</code>

📝 <b>Core Skills:</b>
${profile.skills.map(s => `• ${escapeHtml(s)}`).join('\n') || '<i>None specified</i>'}

⚙️ <b>Tech & Tools:</b>
${profile.technologies.slice(0, 8).map(t => `• ${escapeHtml(t)}`).join('\n') || '<i>None specified</i>'}

🚫 <b>Excluded Categories:</b>
${profile.excludedCategories.map(ec => `• ${escapeHtml(ec)}`).join('\n') || '<i>None set</i>'}
      `;
      await sendReply(chatId, info.trim(), 'HTML');
      return;
    }

    if (command === '/match') {
      const ops = db.getOpportunities()
        .filter(o => o.matchAnalysis && o.matchAnalysis.score >= 70 && o.status === 'ACTIVE' && o.validationStatus === 'VALID');
      if (ops.length === 0) {
        await sendReply(chatId, `⭐ <b>High-Match Opportunity Matches</b>\n\nThere are no validated high-compatibility (70%+) positions currently in active state.\nRun <code>/scrape</code> to find fresh matches.`, 'HTML');
        return;
      }
      const responseLines = [
        `⭐ <b>Best Active Opportunities Matches (>= 70%)</b>`,
        `----------------------------------------`
      ];
      ops.slice(0, 6).forEach((o, i) => {
        responseLines.push(
          `<b>${i + 1}.</b> <a href="${o.link}">[${escapeHtml(o.platform)}] <b>${escapeHtml(o.title)}</b></a>\nBudget: <b>${escapeHtml(o.budget)}</b> | Score: ⭐ <b>${o.matchAnalysis?.score}%</b>\nAnalysis: <i>${escapeHtml(o.matchAnalysis?.reasoning?.substring(0, 110))}...</i>`
        );
      });
      await sendReply(chatId, responseLines.join('\n\n'), 'HTML');
      return;
    }

    if (command === '/status') {
      const ops = db.getOpportunities();
      const props = db.getProposals();
      const autoSettings = db.getAutomationSettings();
      const accounts = db.getAccounts();
      const logs = db.getLogs().slice(0, 3);

      const totalOps = ops.length;
      const activeOps = ops.filter(o => o.isActive !== false && o.validationStatus === 'VALID').length;
      const totalProps = props.length;
      const submittedProps = props.filter(p => p.status === 'submitted').length;

      const accountLines = accounts.map(a => {
        const statusEmoji = a.status === 'CONNECTED' ? '🟢' : a.status === 'EXPIRED' ? '🔴' : '🟡';
        return `• ${statusEmoji} <b>${escapeHtml(a.platform)}</b>: <i>${escapeHtml(a.status)}</i> (${escapeHtml(a.username || 'Not paired')})`;
      }).join('\n');

      const logsLines = logs.map(l => {
        const emoji = l.type === 'success' ? '✅' : l.type === 'error' ? '❌' : l.type === 'warning' ? '⚠️' : 'ℹ️';
        return `• [${escapeHtml(l.source.toUpperCase())}] ${emoji} <i>${escapeHtml(l.message)}</i>`;
      }).join('\n');

      const statusText = `
⚙️ <b>System Live Status & Metrics</b>
----------------------------------------
🤖 <b>Automation Mode</b>: <code>${autoSettings.mode.toUpperCase()}</code>
⏱ <b>Scraper Rate</b>: <code>Every ${autoSettings.scrapeIntervalMinutes} mins</code>
📬 <b>Auto-Approve Threshold</b>: <code>${autoSettings.autoApproveMinScore}%</code>

💼 <b>Platform Configurations:</b>
${accountLines || '<i>No accounts active</i>'}

📊 <b>Opportunities Summary:</b>
• Total Crawled: <b>${totalOps}</b>
• Verified Active Healthy: <b>${activeOps}</b>
• Draft Outbox Queue: <b>${totalProps}</b>
• Auto-Submitted Bids: <b>${submittedProps}</b>

🪵 <b>Latest System Logs:</b>
${logsLines || '<i>No recent logs recorded.</i>'}
      `;
      await sendReply(chatId, statusText.trim(), 'HTML');
      return;
    }

    if (command === '/scrape') {
      await sendReply(chatId, `🔄 <b>Crawling Active Platforms...</b>\n\nYour background crawler engines are logging into Khamsat, Mostaql, and Fiverr and scanning search channels. This might take 15 to 40 seconds. Please hold...`, 'HTML');

      try {
        const { triggerActivePlatformsScrape } = await import('./scraper.js');
        const newCount = await triggerActivePlatformsScrape();
        await sendReply(chatId, `✅ <b>Scrape Cycle Complete!</b>\n\nAdded <b>${newCount}</b> brand new validated freelance opportunities to your database queue! Use <code>/khamsat</code> or <code>/mostaql</code> to browse detailed lists.`, 'HTML');
      } catch (err: any) {
        await sendReply(chatId, `❌ <b>Scraper Error</b>\n\nFailed to complete the scrape cycle: ${escapeHtml(err.message || 'Unknown issue')}`, 'HTML');
      }
      return;
    }

    if (command === '/revalidate') {
      await sendReply(chatId, `🔍 <b>Revalidating Opportunity Channels...</b>\n\nInitiating active health checks against pending database links. Evaluating page content, deleted status codes, and redirects. This may take 10 to 30 seconds...`, 'HTML');

      try {
        const { revalidateSavedOpportunities } = await import('./scraper.js');
        await revalidateSavedOpportunities();
        await sendReply(chatId, `✅ <b>Revalidation Cycle Complete!</b>\n\nAll pending and active opportunities verified. Invalid, expired, and closed projects have been flagged with closed states in the database.`, 'HTML');
      } catch (err: any) {
        await sendReply(chatId, `❌ <b>Revalidation Error</b>\n\nFailed to complete revalidation checks: ${escapeHtml(err.message || 'Unknown issue')}`, 'HTML');
      }
      return;
    }

    if (command === '/briefing') {
      await sendReply(chatId, `📊 <b>Generating Daily Briefing...</b>`, 'HTML');
      try {
        await sendDailyBriefingReport();
      } catch (err: any) {
        await sendReply(chatId, `❌ <b>Briefing Generation Failed</b>: ${escapeHtml(err.message)}`, 'HTML');
      }
      return;
    }

    // Unrecognized command
    await sendReply(chatId, `⚠️ <b>Unrecognized Command</b>\n\nSend <code>/help</code> to see the list of supported slash commands.`, 'HTML');
    return;
  }

  // Handle Conversational Text Messages via Gemini Co-Pilot Coordinator
  try {
    const { getGeminiClient, isGeminiConfigured } = await import('./gemini.js');
    if (!isGeminiConfigured()) {
      await sendReply(chatId, `⚠️ <b>Gemini AI API Key is not configured yet.</b>\n\nPlease go to your AI Studio Secrets panel, check your environment files, or configure your key under Settings so I can assist you with interactive AI features!`, 'HTML');
      return;
    }

    await fetch(
      `https://api.telegram.org/bot${currentSettings.botToken}/sendChatAction`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ chat_id: chatId, action: 'typing' })
      }
    ).catch(() => {});

    const profile = db.getProfile();
    const recentOps = db.getOpportunities()
      .filter(o => o.status === 'ACTIVE' && o.validationStatus === 'VALID')
      .slice(0, 5);

    const opsContext = recentOps.map((o, idx) => {
      return `Opportunity ${idx + 1}:
ID: ${o.id}
Platform: ${o.platform}
Title: ${o.title}
Budget: ${o.budget}
Description: ${o.description.substring(0, 200)}...
Link: ${o.link}
`;
    }).join('\n\n');

    const systemInstruction = `
You are the elite AI Freelance Bot Assistant ("Freelance OS Co-Pilot") for this chatbot.
The user is a professional freelancer chatting with you from their Telegram messenger.

Freelancer Profile:
Experience Level: ${profile.experience}
Preferred rate: $${profile.hourlyRate}/hr
Preferred Min Budget: $${profile.preferredMinBudget}
Target project styles: ${profile.projectTypes.join(', ')}
Skills: ${profile.skills.join(', ')}
Technologies: ${profile.technologies.join(', ')}
Excluded limits: ${profile.excludedCategories.join(', ')}

Here are some of their currently active, verified workspace opportunities for context:
${opsContext || 'No active jobs currently in database.'}

Your rules:
1. Be concise, expert, helpful, and direct. Keep formatting neat and matching Telegram's Markdown parsing rules. Keep it professional.
2. If they ask questions in Arabic, reply in professional Arabic. If English, reply in English. Match their language naturally.
3. Keep response message size strict (less than 3200 chars) to prevent Telegram API buffer overflows.
4. You are their professional co-pilot. You can assist them with suggestions on how to improve bids, pitch for a specific job listed in their queue, or answer questions about tech development or client management.
    `;

    const ai = getGeminiClient();
    const activeSettings = db.getAutomationSettings();
    const activeModel = activeSettings.geminiModel || 'gemini-2.5-flash';

    const response = await ai.models.generateContent({
      model: activeModel,
      contents: text,
      config: { systemInstruction }
    });

    const generatedText = response.text || "I was unable to formulate a response.";
    await sendReply(chatId, generatedText, 'Markdown');
  } catch (err: any) {
    await sendReply(chatId, `❌ <b>Co-Pilot AI Exception</b>\n\nUnable to generate reply: ${escapeHtml(err.message || 'Transient error')}`, 'HTML');
  }
}

/**
 * Polling controller declarations.
 */
let pollerActive = false;
let runningBotToken = '';

export function stopTelegramPolling() {
  pollerActive = false;
  runningBotToken = '';
}

export function startTelegramPolling() {
  const settings = db.getTelegramSettings();
  if (!settings.enabled || !settings.botToken) {
    db.addLog('info', 'telegram', 'Telegram bot polling skipped: Settings incomplete or disabled.');
    stopTelegramPolling();
    return;
  }

  // If the poller is already running and the token hasn't changed, reuse thread
  if (pollerActive && runningBotToken === settings.botToken) {
    return;
  }

  // If it's running with a DIFFERENT token, shut it down first so the old fetch completes
  if (pollerActive && runningBotToken !== settings.botToken) {
    db.addLog('info', 'telegram', 'Bot Token change detected. Terminating running loop and starting fresh...');
    pollerActive = false;
  }

  pollerActive = true;
  runningBotToken = settings.botToken;
  db.addLog('success', 'telegram', 'Telegram interactive chatbot loop initiated.');

  (async () => {
    let offset = 0;
    const initialToken = settings.botToken;

    while (pollerActive && runningBotToken === initialToken) {
      const currentSettings = db.getTelegramSettings();
      if (!currentSettings.enabled || !currentSettings.botToken || currentSettings.botToken !== initialToken) {
        db.addLog('info', 'telegram', 'Telegram bot thread exiting naturally due to configuration update.');
        break;
      }

      try {
        const response = await fetch(
          `https://api.telegram.org/bot${initialToken}/getUpdates?offset=${offset}&timeout=20`,
          { method: 'GET', signal: AbortSignal.timeout(30000) }
        ).catch(() => null);

        if (!response) {
          await new Promise(resolve => setTimeout(resolve, 5000));
          continue;
        }

        const data = await response.json() as any;
        if (!data.ok) {
          db.addLog('warning', 'telegram', `Telegram server update check blocked: ${data.description || 'check credentials'}`);
          await new Promise(resolve => setTimeout(resolve, 10000));
          continue;
        }

        const updates = data.result || [];
        for (const update of updates) {
          offset = update.update_id + 1;
          if (update.message) {
            await handleIncomingTelegramMessage(update.message);
          }
        }
      } catch (err: any) {
        await new Promise(resolve => setTimeout(resolve, 5000));
      }

      await new Promise(resolve => setTimeout(resolve, 500));
    }

    if (runningBotToken === initialToken) {
      pollerActive = false;
      runningBotToken = '';
    }
  })();
}

/**
 * Active Scheduler check loop to call daily briefing
 */
let schedulerIntervalId: NodeJS.Timeout | null = null;
let lastBriefingDateStr = '';

export function startScheduler() {
  if (schedulerIntervalId) {
    clearInterval(schedulerIntervalId);
  }

  // Automatically start/refresh Telegram Bot polling loop
  startTelegramPolling();

  // Check every 60s
  schedulerIntervalId = setInterval(async () => {
    const settings = db.getTelegramSettings();
    if (!settings.enabled || !settings.botToken || !settings.chatId) return;

    const now = new Date();
    const currentHourMin = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;
    const todayDateStr = now.toDateString();

    if (currentHourMin === settings.reportTime && lastBriefingDateStr !== todayDateStr) {
      lastBriefingDateStr = todayDateStr;
      db.addLog('info', 'telegram', `Triggering scheduled Daily Briefing Report at ${settings.reportTime}`);
      await sendDailyBriefingReport();
    }
  }, 60000);
}
